import {describe,expect,it} from 'vitest'
import {createMatch} from './data'
import {applyRound,resolveRound} from './engine'
import type {Asset,Point} from './types'

const edgeRoute=(match:ReturnType<typeof createMatch>):Point[]=>{const base=match.world.friendlyTerritory.center;return [base,[base[0],base[1]>=0?match.world.bounds.minZ-8:match.world.bounds.maxZ+8]]}
const onlyRaven=(match:ReturnType<typeof createMatch>)=>({...match,squadrons:match.squadrons.map(squadron=>squadron.id==='raven'?{...squadron,aggression:'aggressive' as const,route:edgeRoute(match),routeIngress:edgeRoute(match)}:{...squadron,aircraft:0,strength:0})})

describe('reconnaissance exploration recovery',()=>{
  it('commits in-bounds mapping and an observed edge only after recon recovers',()=>{const match=onlyRaven(createMatch(7301)),result=resolveRound(match);expect(result.squadrons.find(squadron=>squadron.id==='raven')?.status).toBe('rtb');expect(result.mappedAreas.length).toBeGreaterThan(0);expect(result.mappedAreas.every(point=>point[0]>=match.world.bounds.minX&&point[0]<=match.world.bounds.maxX&&point[1]>=match.world.bounds.minZ&&point[1]<=match.world.bounds.maxZ)).toBe(true);expect(result.discoveredBoundaries.length).toBeGreaterThan(0);expect(result.events.some(event=>event.title==='WORLD EDGE DISCOVERED')).toBe(true);const applied=applyRound(match,result);expect(applyRound(applied,result).discoveredBoundaries).toEqual(applied.discoveredBoundaries)})
  it('commits observations when doctrine aborts the flight but the recon formation returns home',()=>{const initial=createMatch(7301),base=initial.world.friendlyTerritory.center,direction=base[1]>=0?-1:1,route:Point[]=[base,[base[0],base[1]+direction*9]],sam:Asset={id:'abort-sam',kind:'sam',position:[base[0],base[1]+direction*3],intel:'unknown',confidence:0,health:100,maxHealth:100,hidden:true,struck:false},match={...initial,enemyAssets:[sam],squadrons:initial.squadrons.map(squadron=>squadron.id==='raven'?{...squadron,aggression:'conservative' as const,route,routeIngress:route}:{...squadron,aircraft:0,strength:0})},result=resolveRound(match);expect(result.behaviorIntervals.some(interval=>interval.unitId==='raven'&&interval.mode==='recovering')).toBe(true);expect(result.squadrons.find(squadron=>squadron.id==='raven')?.status).toBe('rtb');expect(result.mappedAreas.length).toBeGreaterThan(0)})
  it('drops provisional mapping and boundary observations when recon is destroyed',()=>{const baseMatch=onlyRaven(createMatch(7301)),route=edgeRoute(baseMatch),[base]=route;const defenses:Asset[]=Array.from({length:8},(_,index)=>({id:`loss-sam-${index}`,kind:'sam',position:[base[0],base[1]+(base[1]>=0?-1:1)*(1.1+index*.05)] as Point,intel:'unknown',confidence:0,health:100,maxHealth:100,hidden:true,struck:false}));const match={...baseMatch,enemyAssets:defenses,squadrons:baseMatch.squadrons.map(squadron=>squadron.id==='raven'?{...squadron,aircraft:1,maxAircraft:1,strength:1}:squadron)},result=resolveRound(match);expect(result.squadrons.find(squadron=>squadron.id==='raven')?.status).toBe('destroyed');expect(result.mappedAreas).toEqual([]);expect(result.discoveredBoundaries).toEqual([])})
  it('does not repeat an already-known asset in the after-action intelligence report',()=>{const initial=createMatch(7301),base=initial.world.friendlyTerritory.center,position=[base[0],base[1] - 4] as Point,known:Asset={id:'known-radar',kind:'radar',position,intel:'confirmed',confidence:90,health:100,maxHealth:100,hidden:false,struck:false},route:[Point,Point,Point]=[base,position,base],match={...initial,enemyAssets:[known],squadrons:initial.squadrons.map(squadron=>squadron.id==='raven'?{...squadron,route,routeIngress:route}:{...squadron,aircraft:0,strength:0})},result=resolveRound(match);expect(result.intelReports).toEqual([]);expect(result.intelGained).toEqual([])})
})
