import type {Asset,BoundarySegment,CampaignWorld,Point,WorldBounds} from './types'
import {MAPPED_RADIUS} from './fog'

export type KnownWorldDirection=BoundarySegment['edge']
export interface KnownTerrainFeature{id:string;kind:'ridge'|'river'|'coastline'|'landmark';points:Point[];label?:string}
export interface KnownWorldInput{mappedAreas:Point[];friendlyTerritory:CampaignWorld['friendlyTerritory'];friendlyAssets:Asset[];enemyAssets:Asset[];discoveredBoundaries:BoundarySegment[];terrainFeatures?:KnownTerrainFeature[]}
export interface KnownBoundaryLine{edge:KnownWorldDirection;from:Point;to:Point}
export interface KnownWorldModel{viewBox:WorldBounds;mappedAreas:Point[];mappedRadius:number;friendlyTerritory:CampaignWorld['friendlyTerritory'];friendlyAssets:Asset[];enemyAssets:Asset[];terrainFeatures:KnownTerrainFeature[];boundaries:KnownBoundaryLine[];unchartedDirections:KnownWorldDirection[]}

const VIEW_PADDING=2.5,DIRECTIONS:KnownWorldDirection[]=['north','east','south','west']
const finitePoint=(point:Point)=>Number.isFinite(point[0])&&Number.isFinite(point[1])
const expand=(bounds:WorldBounds,padding:number):WorldBounds=>({minX:bounds.minX-padding,maxX:bounds.maxX+padding,minZ:bounds.minZ-padding,maxZ:bounds.maxZ+padding})

export function deriveDiscoveredBoundaryLines(segments:BoundarySegment[]):KnownBoundaryLine[]{const seen=new Set<string>(),lines:KnownBoundaryLine[]=[];for(const segment of segments){if(!Number.isFinite(segment.coordinate)||!Number.isFinite(segment.from)||!Number.isFinite(segment.to))continue;const from=Math.min(segment.from,segment.to),to=Math.max(segment.from,segment.to),key=`${segment.edge}:${segment.coordinate}:${from}:${to}`;if(seen.has(key))continue;seen.add(key);if(segment.edge==='north'||segment.edge==='south')lines.push({edge:segment.edge,from:[from,segment.coordinate],to:[to,segment.coordinate]});else lines.push({edge:segment.edge,from:[segment.coordinate,from],to:[segment.coordinate,to]})}return lines}

function knownBounds(input:KnownWorldInput,boundaries:KnownBoundaryLine[]):WorldBounds{const territory=input.friendlyTerritory;const bounds:WorldBounds={minX:territory.center[0]-territory.radius,maxX:territory.center[0]+territory.radius,minZ:territory.center[1]-territory.radius,maxZ:territory.center[1]+territory.radius};const points:Point[]=[...input.friendlyAssets.map(asset=>asset.position),...input.enemyAssets.map(asset=>asset.position),...(input.terrainFeatures??[]).flatMap(feature=>feature.points),...boundaries.flatMap(boundary=>[boundary.from,boundary.to])].filter(finitePoint);for(const point of input.mappedAreas.filter(finitePoint)){bounds.minX=Math.min(bounds.minX,point[0]-MAPPED_RADIUS);bounds.maxX=Math.max(bounds.maxX,point[0]+MAPPED_RADIUS);bounds.minZ=Math.min(bounds.minZ,point[1]-MAPPED_RADIUS);bounds.maxZ=Math.max(bounds.maxZ,point[1]+MAPPED_RADIUS)}for(const point of points){bounds.minX=Math.min(bounds.minX,point[0]);bounds.maxX=Math.max(bounds.maxX,point[0]);bounds.minZ=Math.min(bounds.minZ,point[1]);bounds.maxZ=Math.max(bounds.maxZ,point[1])}return bounds}

export function deriveKnownWorldModel(input:KnownWorldInput):KnownWorldModel{const enemyAssets=[...input.enemyAssets].filter(asset=>!asset.hidden&&(asset.intel==='probable'||asset.intel==='confirmed')).sort((a,b)=>a.id.localeCompare(b.id)),friendlyAssets=[...input.friendlyAssets].sort((a,b)=>a.id.localeCompare(b.id)),terrainFeatures=[...(input.terrainFeatures??[])].filter(feature=>feature.points.length>0&&feature.points.every(finitePoint)).sort((a,b)=>a.id.localeCompare(b.id)),boundaries=deriveDiscoveredBoundaryLines(input.discoveredBoundaries),knownEdges=new Set(boundaries.map(boundary=>boundary.edge));return {viewBox:expand(knownBounds({...input,friendlyAssets,enemyAssets,terrainFeatures},boundaries),VIEW_PADDING),mappedAreas:input.mappedAreas.filter(finitePoint).map(point=>[...point]),mappedRadius:MAPPED_RADIUS,friendlyTerritory:{center:[...input.friendlyTerritory.center],radius:input.friendlyTerritory.radius},friendlyAssets,enemyAssets,terrainFeatures,boundaries,unchartedDirections:DIRECTIONS.filter(direction=>!knownEdges.has(direction))}}
export const knownWorldViewBox=(bounds:WorldBounds)=>`${bounds.minX} ${-bounds.maxZ} ${bounds.maxX-bounds.minX} ${bounds.maxZ-bounds.minZ}`
