import {describe,expect,it} from 'vitest'
import {boundarySegmentsObservedAt,createStartingKnowledge,deriveKnownEnvelope,derivePlanningEnvelope,generateCampaignWorld,generateMultiplayerStartAnchors,intersectMovementWithWorld,isPointMapped,mergeBoundarySegments} from './world'

describe('campaign world',()=>{
  it('generates deterministic 28 by 36 bounds and one valid central start',()=>{const first=generateCampaignWorld(5473);expect(first).toEqual(generateCampaignWorld(5473));expect(first.bounds).toEqual({minX:-14,maxX:14,minZ:-18,maxZ:18});expect(first.presentationBounds.minX).toBeLessThanOrEqual(first.bounds.minX-6);expect(first.presentationBounds.maxZ).toBeGreaterThanOrEqual(first.bounds.maxZ+6);expect(Math.abs(first.friendlyTerritory.center[0])).toBe(3);expect(Math.abs(first.friendlyTerritory.center[1])).toBe(4);expect(first.friendlyTerritory.radius).toBe(4.5)})
  it('seeds only local knowledge and derives planning limits without true bounds',()=>{const world=generateCampaignWorld(7301),knowledge=createStartingKnowledge(world),known=deriveKnownEnvelope(world,knowledge.mappedAreas,knowledge.discoveredBoundaries),planning=derivePlanningEnvelope(known);expect(knowledge.discoveredBoundaries).toEqual([]);expect(knowledge.mappedAreas.length).toBeGreaterThan(20);expect(isPointMapped(world.friendlyTerritory.center,{mappedAreas:[],friendlyTerritory:world.friendlyTerritory})).toBe(true);expect(isPointMapped([known.maxX+3,known.maxZ+3],{mappedAreas:knowledge.mappedAreas,friendlyTerritory:world.friendlyTerritory})).toBe(false);expect(planning.minX).toBe(known.minX-4);expect(planning.maxZ).toBe(known.maxZ+4)})
  it('produces edge-cleared separated multiplayer anchors without enabling multiplayer state',()=>{const bounds=generateCampaignWorld(1).bounds,starts=generateMultiplayerStartAnchors(99,4,bounds);expect(starts).toEqual(generateMultiplayerStartAnchors(99,4,bounds));for(const start of starts){expect(start[0]-bounds.minX).toBeGreaterThanOrEqual(3.5);expect(bounds.maxX-start[0]).toBeGreaterThanOrEqual(3.5);expect(start[1]-bounds.minZ).toBeGreaterThanOrEqual(3.5);expect(bounds.maxZ-start[1]).toBeGreaterThanOrEqual(3.5)}for(const [index,start] of starts.entries())for(const other of starts.slice(index+1))expect(Math.hypot(start[0]-other[0],start[1]-other[1])).toBeGreaterThanOrEqual(4.5)})
  it('clips at the first true boundary and merges exact recovered segments idempotently',()=>{const bounds=generateCampaignWorld(1).bounds;expect(intersectMovementWithWorld([0,0],[20,5],bounds)).toMatchObject({edge:'east',point:[14,3.5]});const observed=boundarySegmentsObservedAt([14,0],2.65,bounds);expect(observed).toEqual([{edge:'east',coordinate:14,from:-2.65,to:2.65}]);const merged=mergeBoundarySegments([{edge:'east',coordinate:14,from:-2,to:1}],[{edge:'east',coordinate:14,from:.5,to:3},{edge:'north',coordinate:18,from:-1,to:1}]);expect(merged).toEqual([{edge:'north',coordinate:18,from:-1,to:1},{edge:'east',coordinate:14,from:-2,to:3}]);expect(mergeBoundarySegments(merged,merged)).toEqual(merged)})
})
