import {memo} from 'react'
import type {Asset,Point} from '../game/types'
import {knownWorldViewBox} from '../game/knownWorld'
import type {KnownTerrainFeature,KnownWorldDirection,KnownWorldModel} from '../game/knownWorld'

export interface KnownWorldMapProps{model:KnownWorldModel;title?:string;onClose?:()=>void}
const pointList=(points:Point[])=>points.map(point=>`${point[0]},${-point[1]}`).join(' ')
function TerrainFeature({feature}:{feature:KnownTerrainFeature}){return <g className={`known-world-map__feature known-world-map__feature--${feature.kind}`}><polyline points={pointList(feature.points)}/>{feature.label?<text x={feature.points[0][0]} y={-feature.points[0][1]-.35}>{feature.label}</text>:null}</g>}
function AssetMark({asset,friendly}:{asset:Asset;friendly:boolean}){const [x,z]=asset.position,label=asset.kind==='base'?(friendly?'HOME':'BASE'):asset.kind.toUpperCase();return <g className={`known-world-map__asset ${friendly?'is-friendly':'is-hostile'}`} transform={`translate(${x} ${-z})`}>{friendly?<circle r="0.22"/>:<rect x="-0.18" y="-0.18" width="0.36" height="0.36" transform="rotate(45)"/>}<text y="-0.38">{label}</text></g>}
function UnchartedLabel({direction,model}:{direction:KnownWorldDirection;model:KnownWorldModel}){const {minX,maxX,minZ,maxZ}=model.viewBox,centerX=(minX+maxX)/2,centerY=-(minZ+maxZ)/2;if(direction==='north')return <text className="known-world-map__uncharted" x={centerX} y={-maxZ+.65}>UNCHARTED · NORTH</text>;if(direction==='south')return <text className="known-world-map__uncharted" x={centerX} y={-minZ-.35}>UNCHARTED · SOUTH</text>;if(direction==='east')return <text className="known-world-map__uncharted" x={maxX-.65} y={centerY} transform={`rotate(90 ${maxX-.65} ${centerY})`}>UNCHARTED · EAST</text>;return <text className="known-world-map__uncharted" x={minX+.65} y={centerY} transform={`rotate(-90 ${minX+.65} ${centerY})`}>UNCHARTED · WEST</text>}
export const KnownWorldMap=memo(function KnownWorldMap({model,title='KNOWN WORLD',onClose}:KnownWorldMapProps){const width=model.viewBox.maxX-model.viewBox.minX,height=model.viewBox.maxZ-model.viewBox.minZ;return <section className="known-world-map" aria-label="Known world tactical overview"><header><div><small>INTELLIGENCE PLOT</small><h2>{title}</h2></div><span>UNKNOWN → STALE → OBSERVED</span>{onClose?<button type="button" onClick={onClose} aria-label="Close known world map">CLOSE</button>:null}</header><svg viewBox={knownWorldViewBox(model.viewBox)} role="img" aria-label="Map containing only recovered geographic and fixed-asset intelligence"><defs><radialGradient id="known-world-atmosphere" cx="50%" cy="50%" r="72%"><stop offset="0%" stopColor="#313b2d" stopOpacity=".72"/><stop offset="72%" stopColor="#151b16" stopOpacity=".82"/><stop offset="100%" stopColor="#090d0b" stopOpacity=".98"/></radialGradient><filter id="known-world-soften" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation=".2"/></filter></defs><rect x={model.viewBox.minX} y={-model.viewBox.maxZ} width={width} height={height} fill="url(#known-world-atmosphere)"/><g className="known-world-map__coverage" filter="url(#known-world-soften)">{model.mappedAreas.map((point,index)=><circle key={`${point[0]}-${point[1]}-${index}`} cx={point[0]} cy={-point[1]} r={model.mappedRadius}/>)}<circle className="known-world-map__friendly-territory" cx={model.friendlyTerritory.center[0]} cy={-model.friendlyTerritory.center[1]} r={model.friendlyTerritory.radius}/></g><g>{model.terrainFeatures.map(feature=><TerrainFeature key={feature.id} feature={feature}/>)}</g><g className="known-world-map__boundaries">{model.boundaries.map((boundary,index)=><line key={`${boundary.edge}-${index}`} x1={boundary.from[0]} y1={-boundary.from[1]} x2={boundary.to[0]} y2={-boundary.to[1]}/>)}</g><g>{model.friendlyAssets.map(asset=><AssetMark key={asset.id} asset={asset} friendly/>)}</g><g>{model.enemyAssets.map(asset=><AssetMark key={asset.id} asset={asset} friendly={false}/>)}</g>{model.unchartedDirections.map(direction=><UnchartedLabel key={direction} direction={direction} model={model}/>)}</svg><footer><span><i className="is-friendly"/> FRIENDLY</span><span><i className="is-hostile"/> KNOWN FIXED CONTACT</span><span><i className="is-boundary"/> RECOVERED EDGE</span></footer></section>})
